public class MathematicalClass {
        public Integer addition(Integer a, integer b) {
        integer total = a + b;
        return total;
    }
    public Integer subtraction(Integer a, integer b) {
        integer minus = a - b;
        return minus;
    }
    public Integer multiplication(Integer a, integer b) {
        integer times = a * b;
        return times;
    }
    public Integer division(Integer a, integer b) {
        integer over = a / b;
        return over;
    }
}
