/* public class StudentInfo {
    public StudentInfo() {
        system.debug(' Welcome to my class');

    }
    public void listOfNames(){
        List<string> listOfStudents = new List<string>();
        listOfStudents.add('Wendy');
        listOfStudents.add('Karla');
        listOfStudents.add('Juan');
        listOfStudents.add('Daniela');
        listOfStudents.add('Aaron');
        system.debug(' List of my students : '+ listOfStudents);

    }
} */

public class StudentInfo {
    public static void StudentInfo() {
        system.debug(' Welcome to my class');

    }
    public static void listOfNames(){
        List<string> listOfStudents = new List<string>();
        listOfStudents.add('Wendy');
        listOfStudents.add('Karla');
        listOfStudents.add('Juan');
        listOfStudents.add('Daniela');
        listOfStudents.add('Aaron');
        system.debug(' List of my students : '+ listOfStudents);

    }
}